"""
tkblend - High-performance Blend2D pure vector graphics and modern vector widget library for Tkinter.
Zero TTK theme dependencies.
"""

import logging

# Set default logging handler to avoid "No handler found" warnings
logging.getLogger("tkblend").addHandler(logging.NullHandler())

from tkblend._tkblend import (  # type: ignore
    Color,
    Gradient,
    StyleEngine,
    PseudoState,
    ComputedStyle,
    load_font_face,
    load_font,
    register_font,
    find_system_font,
    get_loaded_fonts,
    get_internal_fonts,
    get_system_fonts,
    get_active_font,
    set_active_font,
    register_font_directory,
    set_emoji_font,
    get_emoji_font,
    clear_all_caches,
    clear_font_cache,
    clear_shadow_cache,
    clear_emoji_cache,
    get_shadow_cache_size,
    get_shadow_cache_bytes,
    set_shadow_cache_limits,
    COMP_OP_SRC_OVER,
    COMP_OP_SRC_COPY,
    COMP_OP_SRC_IN,
    COMP_OP_SRC_OUT,
    COMP_OP_SRC_ATOP,
    COMP_OP_DST_OVER,
    COMP_OP_DST_IN,
    COMP_OP_DST_OUT,
    COMP_OP_DST_ATOP,
    COMP_OP_XOR,
    COMP_OP_CLEAR,
    COMP_OP_PLUS,
    COMP_OP_MULTIPLY,
    COMP_OP_SCREEN,
    COMP_OP_OVERLAY,
    COMP_OP_DARKEN,
    COMP_OP_LIGHTEN,
    EXTEND_PAD,
    EXTEND_REPEAT,
    EXTEND_REFLECT,
)

try:
    from tkblend.surface import (
        Surface,
        LinearGradient,
        RadialGradient,
        Path,
        parse_color,
        clear_caches,
        ColorLike,
        GradientLike,
    )

    from tkblend.canvas import BlendCanvas
    from tkblend.icons import Icons, parse_icon_markup, FA_SOLID, FA_REGULAR, FA_BRANDS, LUCIDE
    from tkblend.font import (
        FontConfig,
        parse_font,
        extract_font_family,
        sync_tk_fonts,
        MissingGlyphError,
        set_glyph_fallback_mode,
        get_glyph_fallback_mode,
        register_glyph_replacement,
        register_glyph_fallback_hook,
        sanitize_text,
        get_similar_glyph,
    )

    from tkblend.theme import (
        Palette,
        DARK_PALETTE,
        LIGHT_PALETTE,
        DRACULA_PALETTE,
        NORD_PALETTE,
        TOKYO_NIGHT_PALETTE,
        CATPPUCCIN_MOCHA_PALETTE,
        CATPPUCCIN_LATTE_PALETTE,
        CYBERPUNK_PALETTE,
        EMERALD_PALETTE,
        EMERALD_FOREST_PALETTE,
        OCEAN_PALETTE,
        SUNSET_PALETTE,
        SUNSET_AMBER_PALETTE,
        MONOKAI_PALETTE,
        MONOKAI_PRO_PALETTE,
        SOLARIZED_DARK_PALETTE,
        SOLARIZED_LIGHT_PALETTE,
        THEME_PRESETS,
        flush_theme_queue,
        get_available_themes,
        ThemeManager,
        get_theme,
        get_palette,
        set_theme,
        set_dark_mode,
        register_theme,
        load_theme_file,
        load_theme_dir,
        add_theme_listener,
        remove_theme_listener,
        resolve_theme_color,
        resolve_color_failsafe,
        resolve_ancestor_bg,
        apply_theme,
        inject_theme,
        detect_system_theme,
        is_system_dark,
        auto_theme,
        stop_auto_theme,
        blend_color_hex,
        adjust_brightness,
        to_tk_hex,
        to_tk_color,
        is_inside_card,
        is_ttkbootstrap_installed,
        cascade_bg_to_children,
    )

    resolve_color = resolve_theme_color

    from tkblend.decorator import BlendDecorator
except ImportError as _err:
    logging.getLogger("tkblend").debug(
        "Tkinter is not available in the current Python environment (%s). UI widgets and canvas are disabled.",
        _err,
    )

__version__ = "0.3.0"

__all__ = [
    # Core Graphics
    "Surface",
    "BlendCanvas",
    "LinearGradient",
    "RadialGradient",
    "Path",
    "Color",
    "Gradient",
    "StyleEngine",
    "PseudoState",
    "ComputedStyle",
    "parse_color",
    "ColorLike",
    "GradientLike",
    "clear_caches",
    # Theme & Palettes
    "Palette",
    "DARK_PALETTE",
    "LIGHT_PALETTE",
    "DRACULA_PALETTE",
    "NORD_PALETTE",
    "TOKYO_NIGHT_PALETTE",
    "CATPPUCCIN_MOCHA_PALETTE",
    "CATPPUCCIN_LATTE_PALETTE",
    "CYBERPUNK_PALETTE",
    "EMERALD_PALETTE",
    "EMERALD_FOREST_PALETTE",
    "OCEAN_PALETTE",
    "SUNSET_PALETTE",
    "SUNSET_AMBER_PALETTE",
    "MONOKAI_PALETTE",
    "MONOKAI_PRO_PALETTE",
    "SOLARIZED_DARK_PALETTE",
    "SOLARIZED_LIGHT_PALETTE",
    "THEME_PRESETS",
    "get_available_themes",
    "ThemeManager",
    "get_theme",
    "get_palette",
    "set_theme",
    "set_dark_mode",
    "register_theme",
    "load_theme_file",
    "load_theme_dir",
    "flush_theme_queue",
    "add_theme_listener",
    "remove_theme_listener",
    "blend_color_hex",
    "adjust_brightness",
    "to_tk_hex",
    "to_tk_color",
    "resolve_theme_color",
    "resolve_color",
    "resolve_color_failsafe",
    "resolve_ancestor_bg",
    "apply_theme",
    "inject_theme",
    "detect_system_theme",
    "is_system_dark",
    "auto_theme",
    "stop_auto_theme",
    "is_inside_card",
    "is_ttkbootstrap_installed",
    "cascade_bg_to_children",
    # Decorator
    "BlendDecorator",
    # Font Management & Typography
    "load_font_face",
    "load_font",
    "register_font",
    "find_system_font",
    "get_loaded_fonts",
    "get_internal_fonts",
    "get_system_fonts",
    "get_active_font",
    "set_active_font",
    "register_font_directory",
    "set_emoji_font",
    "get_emoji_font",
    "FontConfig",
    "parse_font",
    "extract_font_family",
    "sync_tk_fonts",
    "Icons",
    "parse_icon_markup",
    "FA_SOLID",
    "FA_REGULAR",
    "FA_BRANDS",
    "LUCIDE",
    # Composition Operators & Extend Modes
    "COMP_OP_SRC_OVER",
    "COMP_OP_SRC_COPY",
    "COMP_OP_SRC_IN",
    "COMP_OP_SRC_OUT",
    "COMP_OP_SRC_ATOP",
    "COMP_OP_DST_OVER",
    "COMP_OP_DST_IN",
    "COMP_OP_DST_OUT",
    "COMP_OP_DST_ATOP",
    "COMP_OP_XOR",
    "COMP_OP_CLEAR",
    "COMP_OP_PLUS",
    "COMP_OP_MULTIPLY",
    "COMP_OP_SCREEN",
    "COMP_OP_OVERLAY",
    "COMP_OP_DARKEN",
    "COMP_OP_LIGHTEN",
    "EXTEND_PAD",
    "EXTEND_REPEAT",
    "EXTEND_REFLECT",
    "ctk",
]


def __getattr__(name: str):
    if name == "ctk":
        import importlib
        mod = importlib.import_module("tkblend.ctk")
        globals()["ctk"] = mod
        return mod
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
